### ISSUE TITLE
プレビュー用URLから `ABOUT` ページにとぶと、本番URLのページに遷移してしまう

### ISSUE THREAD

**Issue by jacoyutorius** [code-for-hamamatsu/vaccinecert-faq#87]
## 起こっている問題 / The Problem
- https://fix-84-url-word-wrap.dchofm2ginq7s.amplifyapp.com/
  - を開いて、ナビバーの `ABOUT` をクリックすると本番環境のaboutページに遷移する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by euledge** [comment]
Aboutページだけじゃなくて、全ページ本番へのリンクになってます
![image](https://user-images.githubusercontent.com/1209580/147372965-d02cfb53-1600-45d4-9622-d095e8ab2704.png)

Slackの以下の話だと思います
https://jaws-ug-hamamatsu.slack.com/archives/C0111LQQP71/p1640185117149000
https://jaws-ug-hamamatsu.slack.com/archives/C0111LQQP71/p1640187347155200

**Comment by euledge** [comment]
以下の設定してみました。
これでmainは本番URL、プレビューはAmplifyのURLに切り替えできます

## 環境変数の設定

![image](https://user-images.githubusercontent.com/1209580/147396278-a4cba709-3770-46e0-a0ae-745dcaea338f.png)

## amplify.yml

ブランチがmainなら $BASE_URLをそのまま、それ以外はブランチ名を変換して$BASE_URLを付加したものとする

``` yaml
version: 1
frontend:
  phases:
    build:
      commands:
        - git submodule update --init
        - URL=`[ "$AWS_BRANCH" = "main" ] && echo $BASE_URL || echo https://${AWS_BRANCH/\//-}$BASE_URL`
        - hugo --minify --baseURL=$URL
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths: []
```
